### PR TITLE
Added check for existing .dlls

### PR DESCRIPTION
**Pull request by LarsK1**
Added a check, if a file wasn't deleted in the startup, so nuitka won't try and error to copy a dll.
See #96

### CODE REVIEW

**Comment by LarsK1** [comment]
Hey,
no the chmod part ist really important because in Windows all system DLL are read-only by default. (Only the one in /Windows/System32)
Lars

**Comment by kayhayen** [comment]
Hello Lars,

so I was mistaken in assuming this was a running program causing locking
issues, instead of its an inherited read only flag?

We shouldn't copy system DLLs at all and add them to the listing of things
that can be expected on the target system whereever
possible.

The names of the DLLs you gave sounded very similar to the system one we
listed to not be included in the hotfix.

Is there a way, you could tell the origin of those DLLs ? Date same as the
other icuu.dll or what it was? Because then, we
could just add them to the list, if we were sure it's a system DLL.

I will check my system when I reboot if I have these DLLs maybe too.

I am a bit confused, as to why no other DLLs would have the read only flag.
We ought to just not set it.

The code seems to be such:

        target_path = os.path.join(
            dist_dir,
            dll_name
        )

        shutil.copy(
            dll_filename,
            target_path
        )

I think it would take copy2 or something, to preserve a read only flag, no?

Yours,
Kay

**Comment by kayhayen** [comment]
Just checking docs:

shutil.copy(src, dst)
Copy the file src to the file or directory dst. If dst is a directory, a file with the same basename as src is created (or overwritten) in the directory specified. Permission bits are copied. src and dst are path names given as strings.

shutil.copy2(src, dst)
Similar to shutil.copy(), but metadata is copied as well – in fact, this is just shutil.copy() followed by copystat(). This is similar to the Unix command cp -p.

So, permission bits are copied, and I doubt that is what people want.

Something like this:

        shutil.copy(
            dll_filename,
            open(target_path, "wb")
        )

should prevent it from happening and give stuff default permissions instead. I am going to have a look later.

I am still also surprised, I have no been hit by this before, nothing else installs its DLLs read only?

Because, if there was some sort of guarantee for them to be read only in case of system DLLs, we could use that to detect where Nuitka is missing that kind of flag, could we not? Maybe there is something that does this, so that would be great to know.

Yours,
Kay

**Comment by LarsK1** [comment]
I ran a simple cmd command, to find all read-only dlls:
```
05.06.2012  15:59            25.299 brlm03a.dll
08.02.2017  10:19        11.042.816 gsdll32.dll
08.02.2017  10:19             8.014 gsdll32.lib
19.02.2018  22:04         1.081.128 msdia140.dll
10.06.2016  08:22           106.296 msobj140.dll
20.09.2015  18:50           130.752 symsrv.dll
06.09.2016  23:12           289.568 Microsoft.VisualC.Editor.Implementation.dll
06.09.2016  23:12            41.784 Microsoft.VisualC.QuickSearch.Implementation.dll
06.09.2016  23:12            35.112 Microsoft.VisualStudio.CodeStore.Internal.dll
06.09.2016  23:12            88.864 Microsoft.VisualStudio.CppSvc.Internal.dll
06.09.2016  23:12            23.840 Microsoft.VisualStudio.CxxWiz.Internal.dll
06.09.2016  23:12            21.792 Microsoft.VisualStudio.ResCom.Internal.dll
06.09.2016  23:12            36.152 Microsoft.VisualStudio.VisualC.CallHierarchy.dll
06.09.2016  23:12            50.944 Microsoft.VisualStudio.VsWizard.dll
20.09.2015  18:56            89.440 CppCodeProvider.dll
06.09.2016  23:12            47.360 Microsoft.VisualC.VSCodeProvider.dll
06.09.2016  23:12         2.404.512 cppdebug.dll
06.09.2016  23:12            26.264 dbgeng.dll
06.09.2016  23:12            89.240 ecbuild.dll
06.09.2016  23:12           516.240 mcee.dll
18.07.2016  16:01           329.880 MCppEE.dll
06.09.2016  23:12           107.672 MSEnc.dll
06.09.2016  23:12         1.447.072 NatDbgDE.dll
06.09.2016  23:12           325.280 NatDbgEE.dll
06.09.2016  23:12            31.392 vcencbld.dll
06.09.2016  23:12           310.464 vcconvertengine.dll
06.09.2016  23:12           359.120 VCProjectConversion.dll
06.09.2016  23:12            38.184 Microsoft.VisualStudio.ComponentModelHost.dll
19.02.2018  22:04         1.080.968 msdia140.dll
19.02.2018  21:06         1.390.376 msdia140.dll
19.02.2018  21:48           986.664 msdia140.dll
08.12.2017  13:58             2.535 afxdllx.h
08.12.2017  13:58             3.142 afxdll_.h
08.12.2017  13:58             1.633 afxv_dll.h
19.02.2018  22:04            24.208 mfcmifc80.dll
19.02.2018  21:06            24.208 mfcmifc80.dll
08.12.2017  13:58            24.024 dllinit.cpp
08.12.2017  13:58             7.141 dllmodul.cpp
08.12.2017  13:58             2.207 mfcdll.rc
08.12.2017  13:58             3.731 oledll.cpp
13.02.2018  15:29             7.047 rawdllmainproxy.c
08.12.2017  13:58             2.211 postdllmain.cpp
08.12.2017  13:58             1.736 postrawdllmain.cpp
19.02.2018  22:04           174.880 atlprov.dll
19.02.2018  22:04         1.373.456 c1.dll
19.02.2018  22:04         4.152.088 c1xx.dll
19.02.2018  22:04         5.195.536 c2.dll
12.12.2017  10:44         3.706.048 d3dcompiler_47.dll
19.02.2018  22:04         1.361.176 dpcmi.dll
19.02.2018  22:04           106.280 msobj140.dll
19.02.2018  22:04           276.264 mspdb140.dll
19.02.2018  22:04           429.872 mspdbcore.dll
19.02.2018  22:04           412.448 mspdbst.dll
19.02.2018  22:04         1.769.096 mspft140.dll
19.02.2018  22:04           973.104 msvcdis140.dll
19.02.2018  22:04            78.120 pgodb140.dll
19.02.2018  22:04            50.320 pgort140.dll
19.02.2018  22:13            42.640 atlprovui.dll
19.02.2018  22:13            24.720 bscmakeui.dll
19.02.2018  22:13           619.648 clui.dll
19.02.2018  22:13            21.128 cvtresui.dll
19.02.2018  22:13           102.024 linkui.dll
19.02.2018  22:13            22.168 mspdbcmfui.dll
19.02.2018  22:13           103.568 mspft140ui.dll
19.02.2018  22:13            29.832 nmakeui.dll
19.02.2018  22:13            27.800 pgort140ui.dll
19.02.2018  22:13            36.992 pgoui.dll
19.02.2018  21:06           220.808 atlprov.dll
19.02.2018  21:06         1.653.360 c1.dll
19.02.2018  21:06         5.265.016 c1xx.dll
19.02.2018  21:06         5.832.312 c2.dll
12.12.2017  10:44         4.467.904 d3dcompiler_47.dll
19.02.2018  21:06         1.378.944 dpcmi.dll
19.02.2018  21:06           140.936 msobj140.dll
19.02.2018  21:06           291.984 mspdb140.dll
19.02.2018  21:06           576.144 mspdbcore.dll
19.02.2018  21:06           555.144 mspdbst.dll
19.02.2018  21:06         2.362.504 mspft140.dll
19.02.2018  21:06         1.238.680 msvcdis140.dll
19.02.2018  21:06            95.376 pgodb140.dll
19.02.2018  21:06            56.968 pgort140.dll
19.02.2018  22:08            42.640 atlprovui.dll
19.02.2018  22:08            24.720 bscmakeui.dll
19.02.2018  22:08           620.160 clui.dll
19.02.2018  22:08            21.128 cvtresui.dll
19.02.2018  22:08           102.024 linkui.dll
19.02.2018  22:08            22.160 mspdbcmfui.dll
19.02.2018  22:08           103.576 mspft140ui.dll
19.02.2018  22:08            29.832 nmakeui.dll
19.02.2018  22:08            27.792 pgort140ui.dll
19.02.2018  22:08            36.992 pgoui.dll
19.02.2018  21:06         1.651.984 c1.dll
19.02.2018  21:06         5.266.712 c1xx.dll
19.02.2018  21:06         5.329.672 c2.dll
19.02.2018  21:06         1.379.096 dpcmi.dll
19.02.2018  21:06            95.528 pgodb140.dll
19.02.2018  21:06           126.752 vcmeta.dll
19.02.2018  22:08           620.312 clui.dll
19.02.2018  22:08           102.024 linkui.dll
19.02.2018  22:08            36.992 pgoui.dll
19.02.2018  21:06         1.743.120 c1.dll
19.02.2018  21:06         5.341.464 c1xx.dll
19.02.2018  21:06         6.007.568 c2.dll
19.02.2018  21:06         1.379.096 dpcmi.dll
19.02.2018  21:06            95.528 pgodb140.dll
19.02.2018  21:06           126.752 vcmeta.dll
19.02.2018  22:08           620.312 clui.dll
19.02.2018  22:08           102.024 linkui.dll
19.02.2018  22:08            36.992 pgoui.dll
19.02.2018  21:48            50.056 pgort140.dll
19.02.2018  21:54            29.584 pgort140ui.dll
19.02.2018  22:04         1.300.240 c1.dll
19.02.2018  22:04         4.087.064 c1xx.dll
19.02.2018  22:04         5.052.688 c2.dll
19.02.2018  22:04         1.361.176 dpcmi.dll
19.02.2018  22:04            78.120 pgodb140.dll
19.02.2018  22:04           102.688 vcmeta.dll
19.02.2018  22:13           619.800 clui.dll
19.02.2018  22:13           102.024 linkui.dll
19.02.2018  22:13            36.992 pgoui.dll
19.02.2018  22:04         1.299.064 c1.dll
19.02.2018  22:04         4.087.424 c1xx.dll
19.02.2018  22:04         4.416.624 c2.dll
19.02.2018  22:04         1.361.024 dpcmi.dll
19.02.2018  22:04            77.960 pgodb140.dll
19.02.2018  22:04           102.528 vcmeta.dll
19.02.2018  22:13           619.792 clui.dll
19.02.2018  22:13           102.024 linkui.dll
19.02.2018  22:13            36.992 pgoui.dll
13.02.2018  15:28               625 dllsupp.cpp
19.02.2018  19:59               636 dllsupp.asm
08.12.2017  13:56               840 dllsupp.asm
13.02.2018  15:28               721 dllmain.cpp
08.12.2017  13:59               853 dllexports.cpp
13.02.2018  15:29             1.128 dllexportsimpl.cpp
19.02.2018  20:02             7.453 dll_dllmain.cpp
13.02.2018  15:28             1.032 dll_dllmain_stub.cpp
08.12.2017  13:56             2.734 vcruntime_dllmain.cpp
19.02.2018  22:04            57.704 Microsoft.VisualC.STLCLR.dll
19.02.2018  21:06            57.544 Microsoft.VisualC.STLCLR.dll
19.02.2018  21:48           273.808 concrt140.dll
19.02.2018  21:48           519.560 msvcp140.dll
19.02.2018  21:48           326.040 vccorlib140.dll
19.02.2018  21:48            70.040 vcruntime140.dll
19.02.2018  21:48           467.336 vcamp140.dll
19.02.2018  21:48           129.416 vcomp140.dll
19.02.2018  21:48           668.048 concrt140d.dll
19.02.2018  21:48           805.776 msvcp140d.dll
19.02.2018  21:48           871.832 vccorlib140d.dll
19.02.2018  21:48           100.256 vcruntime140d.dll
19.02.2018  21:48         1.139.088 vcamp140d.dll
19.02.2018  21:48           150.920 vcomp140d.dll
19.02.2018  21:06           781.616 concrt140d.dll
19.02.2018  21:06         1.001.256 msvcp140d.dll
19.02.2018  21:06         1.015.608 vccorlib140d.dll
19.02.2018  21:06           131.904 vcruntime140d.dll
19.02.2018  21:06         1.369.896 vcamp140d.dll
19.02.2018  21:06        11.455.784 mfc140ud.dll
19.02.2018  21:06           135.464 mfcm140ud.dll
19.02.2018  21:06           213.288 vcomp140d.dll
19.02.2018  22:04           591.152 concrt140d.dll
19.02.2018  22:04           749.872 msvcp140d.dll
19.02.2018  22:04           774.456 vccorlib140d.dll
19.02.2018  22:04           111.936 vcruntime140d.dll
19.02.2018  22:04         1.032.488 vcamp140d.dll
19.02.2018  22:04         8.631.080 mfc140ud.dll
19.02.2018  22:04           121.648 mfcm140ud.dll
19.02.2018  22:04           162.096 vcomp140d.dll
19.02.2018  21:48           510.360 msvcp140.dll
19.02.2018  21:48           320.808 vccorlib140.dll
19.02.2018  21:48            63.048 vcruntime140.dll
19.02.2018  21:48            64.104 vcomp140.dll
19.02.2018  21:48           799.056 msvcp140d.dll
19.02.2018  21:48           871.896 vccorlib140d.dll
19.02.2018  21:48            93.000 vcruntime140d.dll
19.02.2018  21:48            73.904 vcomp140d.dll
19.02.2018  21:06           967.552 msvcp140d.dll
19.02.2018  21:06         1.009.536 vccorlib140d.dll
19.02.2018  21:06           122.248 vcruntime140d.dll
19.02.2018  21:06            80.768 vcomp140d.dll
19.02.2018  22:04           730.856 msvcp140d.dll
19.02.2018  22:04           775.328 vccorlib140d.dll
19.02.2018  22:04           103.864 vcruntime140d.dll
19.02.2018  22:04            71.816 vcomp140d.dll
19.02.2018  21:06           603.008 msvcp140.dll
19.02.2018  21:06           388.992 vccorlib140.dll
19.02.2018  21:06            79.752 vcruntime140.dll
19.02.2018  21:06            68.480 vcomp140.dll
19.02.2018  22:04           419.928 msvcp140.dll
19.02.2018  22:04           263.976 vccorlib140.dll
19.02.2018  22:04            77.528 vcruntime140.dll
19.02.2018  22:04            60.960 vcomp140.dll
19.02.2018  21:06           333.616 concrt140.dll
19.02.2018  21:06           633.120 msvcp140.dll
19.02.2018  21:06           395.568 vccorlib140.dll
19.02.2018  21:06            87.864 vcruntime140.dll
19.02.2018  21:06           545.064 vcamp140.dll
19.02.2018  21:06         6.065.952 mfc140u.dll
19.02.2018  21:06           106.280 mfcm140u.dll
19.02.2018  21:06            46.896 mfc140chs.dll
19.02.2018  21:06            46.888 mfc140cht.dll
19.02.2018  21:06            75.568 mfc140deu.dll
19.02.2018  21:06            65.840 mfc140enu.dll
19.02.2018  21:06            74.544 mfc140esn.dll
19.02.2018  21:06            75.568 mfc140fra.dll
19.02.2018  21:06            73.520 mfc140ita.dll
19.02.2018  21:06            55.080 mfc140jpn.dll
19.02.2018  21:06            54.064 mfc140kor.dll
19.02.2018  21:06            71.464 mfc140rus.dll
19.02.2018  21:06           185.128 vcomp140.dll
19.02.2018  22:04           244.016 concrt140.dll
19.02.2018  22:04           440.104 msvcp140.dll
19.02.2018  22:04           267.568 vccorlib140.dll
19.02.2018  22:04            83.768 vcruntime140.dll
19.02.2018  22:04           400.168 vcamp140.dll
19.02.2018  22:04         4.775.200 mfc140u.dll
19.02.2018  22:04            95.520 mfcm140u.dll
19.02.2018  22:04            46.888 mfc140chs.dll
19.02.2018  22:04            46.896 mfc140cht.dll
19.02.2018  22:04            75.568 mfc140deu.dll
19.02.2018  22:04            65.840 mfc140enu.dll
19.02.2018  22:04            74.536 mfc140esn.dll
19.02.2018  22:04            75.568 mfc140fra.dll
19.02.2018  22:04            73.520 mfc140ita.dll
19.02.2018  22:04            55.088 mfc140jpn.dll
19.02.2018  22:04            54.056 mfc140kor.dll
19.02.2018  22:04            71.472 mfc140rus.dll
19.02.2018  22:04           138.536 vcomp140.dll
06.09.2016  23:12         3.121.808 cpfe.dll
10.06.2016  08:21           128.688 cpfecl.arm.dll
10.06.2016  08:22           132.272 cpfecl.Win32.dll
10.06.2016  08:22           131.752 cpfecl.x64.dll
06.09.2016  23:12           142.000 MacroPicker.dll
06.09.2016  23:12            29.856 vcbuild.dll
20.06.2016  15:45           389.376 Microsoft.Build.CPPTasks.Common.dll
13.06.2018  16:25            20.640 FL_VSTOLoaderUI_dll_122707_122707_x86_deu.3643236F_FC70_11D3_A536_0090278A1BB8.5326715A_77CF_482B_8CA0_13476898242B
13.05.2011  21:39           802.640 ul_msvcr80.dll.844EFBA7_1C24_93B2_FF1F_C8B3B9A1E18E
29.05.2017  17:57           151.800 omnitracking.dll.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           185.592 omnitracking.dll.B174DB33_06F5_4D20_B8FE_7DFED98F1AE5
29.05.2017  17:57         2.378.160 pasmutility.dll.0B8A52BD_3026_43A8_94C7_85DC61732F5B
29.05.2017  17:57           558.824 pcudataintl.dll.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           559.336 pcudataintl.dll1.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll10.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           555.752 pcudataintl.dll11.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll12.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll13.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll14.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll15.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll16.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll17.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           559.336 pcudataintl.dll2.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           559.336 pcudataintl.dll3.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll4.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           554.728 pcudataintl.dll5.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           554.728 pcudataintl.dll6.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           559.848 pcudataintl.dll7.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.824 pcudataintl.dll8.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           558.312 pcudataintl.dll9.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57           555.888 psiclient.dll.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
19.01.2018  20:13            18.368 psiclientbridgeproxy.dll.0B8A52BD_3026_43A8_94C7_85DC61732F5B
19.01.2018  20:13            16.832 psiclientbridgeproxy.dll.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
29.05.2017  17:57            16.616 uhpcunlr.dll.4CC1E308_B8F0_4503_B0E6_1D9DBE2E1620
13.02.2018  23:03           181.912 vscover150.dll_DriverInstall
17.03.2015  01:34           165.536 a3dutils.dll
17.03.2015  01:34           953.504 Ace.dll_NON_OPT
17.03.2015  01:34            79.008 Acrofx32.dll
17.03.2015  01:34           472.736 AcroPDF.dll
17.03.2015  01:34           508.064 acropdf64.dll
17.03.2015  01:34           649.888 AcroPDFImpl.dll
17.03.2015  01:34         1.015.456 AcroPDFImpl64.dll
17.03.2015  01:34        20.722.336 AcroRd32.dll
17.03.2015  01:34        13.348.000 acrord32res.dll
17.03.2015  01:34           115.360 acrosup64.dll
17.03.2015  01:34           511.136 AdobeLinguistic.dll
17.03.2015  01:34           283.296 adoberfp.dll
17.03.2015  01:34           300.192 AdobeXMP.dll
17.03.2015  01:34         5.129.888 AGM.dll
17.03.2015  01:34           244.896 ahclient.dll
17.03.2015  01:34           285.344 AiodLite.dll
17.03.2015  01:34           195.744 AXE8SharedExpat.dll
17.03.2015  01:34           619.680 AXSLE.dll
17.03.2015  01:34           118.432 Bib.dll_NON_OPT
17.03.2015  01:34           157.344 BIBUtils.dll
17.03.2015  01:34           227.328 ccme_asym.dll
17.03.2015  01:34           379.904 ccme_base.dll
17.03.2015  01:34           208.384 ccme_base_non_fips.dll
17.03.2015  01:34           564.736 ccme_ecc.dll
17.03.2015  01:34         2.872.480 CoolType.dll_NON_OPT
17.03.2015  01:34           291.328 cryptocme.dll
17.03.2015  01:34           768.160 JP2KLib.dll
17.03.2015  01:34        34.089.120 libcef.dll.15EE1C08_ED51_465D_B6F3_FB152B1CC435
17.03.2015  01:34           397.984 logsession.dll
17.03.2015  01:34           207.520 nppdf32.dll
17.03.2015  01:34           207.520 nppdf32.dll_Apollo
17.03.2015  01:34         1.593.504 rt3d.dll
17.03.2015  01:34           322.208 sqlite.dll
17.03.2015  01:34            17.056 ViewerPS.dll
18.03.2010  20:31            92.496 System.Net.dll_40client_ref_x86
18.03.2010  20:31            92.496 system.net.dll_ref_x86
29.03.2016  07:03           315.160 F_SirepClient.dll.5731BED7_D35A_4BE7_972C_64E8FF4CDB91
28.06.2017  23:29         1.411.752 BaseToolCore.dll
28.06.2017  23:29           291.496 BlendToolCore.dll
14.05.2011  02:17           632.656 ul_msvcr80.dll.98CB24AD_52FB_DB5F_FF1F_C8B3B9A1E18E
20.06.2016  15:45            28.320 msenv2p.dll
25.10.2017  23:44            21.712 VS14.CHS.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.CHT.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.872 VS14.CSY.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.DEU.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.ESN.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.872 VS14.FRA.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.ITA.TypeScript.Tasks.resources.dll
25.10.2017  23:44            22.392 VS14.JPN.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.KOR.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.PLK.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.PTB.TypeScript.Tasks.resources.dll
25.10.2017  23:44            22.392 VS14.RUS.TypeScript.Tasks.resources.dll
25.10.2017  23:44            21.880 VS14.TRK.TypeScript.Tasks.resources.dll
29.07.2008  12:08           669.184 FL_msdia71_dll_2_60035_x86_ln.3643236F_FC70_11D3_A536_0090278A1BB8
08.08.2018  17:58         1.856.000 icuin.dll
08.08.2018  17:58         1.346.560 icuuc.dll
08.08.2018  17:59            74.752 mdmpostprocessevaluator.dll
08.08.2018  23:41            98.816 MixedRealityCapture.Broker.dll
08.08.2018  23:41           660.992 MixedRealityCapture.Pipeline.dll
08.08.2018  23:41           161.280 SecureAssessmentHandlers.dll
08.08.2018  23:41           162.304 Windows.Management.SecureAssessment.CfgProvider.dll
08.08.2018  23:41            54.272 Windows.Mirage.Internal.Capture.Pipeline.ProxyStub.dll
08.08.2018  17:59         1.615.872 icuin.dll
08.08.2018  17:59         1.155.072 icuuc.dll
08.08.2018  17:59            74.752 mdmpostprocessevaluator.dll
08.08.2018  17:58         1.856.000 icuin.dll
08.08.2018  17:58         1.346.560 icuuc.dll
08.08.2018  23:41            98.816 MixedRealityCapture.Broker.dll
08.08.2018  23:41           660.992 MixedRealityCapture.Pipeline.dll
08.08.2018  23:41            54.272 Windows.Mirage.Internal.Capture.Pipeline.ProxyStub.dll
08.08.2018  23:41           161.280 SecureAssessmentHandlers.dll
08.08.2018  23:41           162.304 Windows.Management.SecureAssessment.CfgProvider.dll
08.08.2018  17:59         1.615.872 icuin.dll
08.08.2018  17:59         1.155.072 icuuc.dll
04.08.2018  09:01         1.847.808 icuin.dll
04.08.2018  09:01         1.351.680 icuuc.dll
04.08.2018  09:01            74.752 mdmpostprocessevaluator.dll
04.08.2018  15:11            98.816 MixedRealityCapture.Broker.dll
04.08.2018  15:11           660.992 MixedRealityCapture.Pipeline.dll
04.08.2018  15:11           161.280 SecureAssessmentHandlers.dll
04.08.2018  15:11           162.304 Windows.Management.SecureAssessment.CfgProvider.dll
04.08.2018  15:11            54.272 Windows.Mirage.Internal.Capture.Pipeline.ProxyStub.dll
04.08.2018  09:01         1.615.872 icuin.dll
04.08.2018  09:01         1.155.072 icuuc.dll
04.08.2018  09:01            74.752 mdmpostprocessevaluator.dll
04.08.2018  09:01         1.847.808 icuin.dll
04.08.2018  09:01         1.351.680 icuuc.dll
04.08.2018  15:11            98.816 MixedRealityCapture.Broker.dll
04.08.2018  15:11           660.992 MixedRealityCapture.Pipeline.dll
04.08.2018  15:11            54.272 Windows.Mirage.Internal.Capture.Pipeline.ProxyStub.dll
04.08.2018  15:11           161.280 SecureAssessmentHandlers.dll
04.08.2018  15:11           162.304 Windows.Management.SecureAssessment.CfgProvider.dll
04.08.2018  09:01         1.615.872 icuin.dll
04.08.2018  09:01         1.155.072 icuuc.dll
```

These are all my PC has.

**Comment by kayhayen** [comment]
I would think that there is no way these are all from original installation, so read only means just nothing really. However, I am fairly sure, these can normally be removed, or else I would have noticed myself, I think. That part is the most confusing to me of all. I need to make my own tests with that it seems. I do not doubt however, that I *ought* to have seen this myself. That read only flag on Windows is a thing.

But, what I was thinking is that "shutil.copy" is something I do not really want to use in Nuitka then, as the copying of permissions makes no sense. I will replace everything with a "copyFile". Then there is also "shutil.copytree" in the Qt plugin, which seems to use "shutil.copy2" internally, which is even worse.

Anyway, that will take time, might take me a while. In the mean time you can use your patch.

**Comment by kayhayen** [comment]
So, this is as simple as using "copyfile" instead of "copy" from the shutil module. It precisely does that, and I changed all uses of "copy" to "copyfile", which fixes the underlying issue. It will be in the pre-release I do later today to develop branch.

Thanks for your report and hard work, this will make Windows out of the box experience even better.

**Pull request closed without merging**
